export enum EventType {
  SHIFT_STARTED = 'SHIFT_STARTED',
  SHIFT_ENDED = 'SHIFT_ENDED',
  GPS_RECORDED = 'GPS_RECORDED',
  APP_STARTED = 'APP_STARTED',
  APP_STOPPED = 'APP_STOPPED',
  SYNC_STARTED = 'SYNC_STARTED',
  SYNC_COMPLETED = 'SYNC_COMPLETED',
  SYNC_FAILED = 'SYNC_FAILED',
  TRACKING_STARTED = 'TRACKING_STARTED',
  TRACKING_STOPPED = 'TRACKING_STOPPED',
  TRACKING_PAUSED = 'TRACKING_PAUSED',
  TRACKING_RESUMED = 'TRACKING_RESUMED',
  LOCATION_REJECTED = 'LOCATION_REJECTED',
  TRACKING_ERROR = 'TRACKING_ERROR',
  ATTENDANCE_CHECKED_IN = 'ATTENDANCE_CHECKED_IN',
  ATTENDANCE_CHECKED_OUT = 'ATTENDANCE_CHECKED_OUT',
  ATTENDANCE_LOCATION_REJECTED = 'ATTENDANCE_LOCATION_REJECTED',
  ATTENDANCE_PERSISTENCE_FAILED = 'ATTENDANCE_PERSISTENCE_FAILED',
  ATTENDANCE_ERROR = 'ATTENDANCE_ERROR'
}

export enum ShiftStatus {
  ACTIVE = 'ACTIVE',
  CLOSED = 'CLOSED'
}

export enum SyncStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED'
}

export enum ConnectivityStatus {
  ONLINE = 'ONLINE',
  OFFLINE = 'OFFLINE',
  UNKNOWN = 'UNKNOWN'
}

export enum TrackingStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  ERROR = 'ERROR'
}
