name: Deploy Database Migrations

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "supabase/migrations/**"

jobs:
  deploy:

    runs-on: ubuntu-latest

    env:
      SUPABASE_DISABLE_TELEMETRY: "1"

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: 2.39.2

      - name: Link Supabase Project
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase link \
            --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}

      - name: Deploy Migrations
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        run: |
          supabase db push --include-all

      - name: List Remote Migration Status
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase migration list